# Generated by Django 6.0.4 on 2026-06-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_priceitem_scheduleentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceitem",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktywny plan"),
        ),
    ]
