# Generated by Django 6.0.4 on 2026-06-24 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_membership_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='membership_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data wygaśnięcia karnetu'),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='duration_months',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 miesiąc'), (3, '3 miesiące'), (6, '6 miesięcy')], verbose_name='Okres karnetu'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='entry_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rodzaj wejścia'),
        ),
        migrations.AlterField(
            model_name='priceitem',
            name='payment_method',
            field=models.CharField(max_length=100, verbose_name='Sposób płatności'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='friday',
            field=models.CharField(blank=True, max_length=100, verbose_name='Piątek'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='monday',
            field=models.CharField(blank=True, max_length=100, verbose_name='Poniedziałek'),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='wednesday',
            field=models.CharField(blank=True, max_length=100, verbose_name='Środa'),
        ),
    ]
